# Generated by Django 5.1.7 on 2025-03-11 20:39

import books.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookborrow',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(storage=books.storages.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=books.storages.PrivateMediaStorage(), upload_to=''),
        ),
    ]
